### ISSUE TITLE
stroke and opacity properties issue on data object

### ISSUE THREAD

**Issue by romainneutron** [uber/react-vis#155] opened 2016-10-14 06:45 UTC
Hello,

First of all, thanks for this library. I'm trying to use the VerticalBarSeries like below and cannot manage to get it working like I would. 
Following the guide ate https://github.com/uber/react-vis/blob/master/docs/xy-plot.md#common-concepts, I expected to be allowed to defined either `stroke`, `opacity`, `fill` or `color` on any data object, however it does not seem to work. For instance using this code, I end up with `{opacity: 0.1, stroke: "#12939A", fill: "#12939A"}` set as style properties.

```
                    <XYPlot
                        width={800}
                        height={300}>
                        <VerticalBarSeries
                            data={source.map(data => ({
                                x: data.key,
                                y: data.doc_count,
                                fill: 'green',
                                stroke: 'red',
                                opacity: 0.4,
                            }))}
                        />
                    </XYPlot>
```

Is it a bug? Am I misusing the library?

Thanks

**Comment by jameskraus** [comment] 2016-11-07 19:33
Would you mind creating an example repo?

**Comment by greatermeans** [comment] 2016-11-22 19:31
+1 this has happened to mine as well. When opacity is manipulated, it defaults to 0.1.

**Comment by mcnuttandrew** [comment] 2016-12-14 23:21
Hey @romainneutron 

Opacity has some particular defaults. Generally I've found it more preferable to use the literal scale type 

`                    <XYPlot
                        width={800}
                        height={300}>
                        <VerticalBarSeries
                            opacityType="literal"
                            data={source.map(data => ({
                                x: data.key,
                                y: data.doc_count,
                                fill: 'green',
                                stroke: 'red',
                                opacity: 0.4,
                            }))}
                        />
                    </XYPlot>`

Which causes the value at hand not to be scaled or manipulated relative to the default. The literal scale type is great for time when you want to exactly specify a color, or a property you know well, such as opacity.

**Comment by mcnuttandrew** [comment] 2017-02-27 18:04
Hey all, 

In the recent major version bump (1.0.0) i modified the way that opacity works by default ot be a little more natural, so that it does not default to 0.1. This should clear up your opacity problems. I haven't been able to reproduce the stroke issues. I am closing this issue, but feel free to re-open if they are still going.

**Closed by mcnuttandrew** 2017-02-27 18:04 UTC

**Comment by akindr** [comment] 2017-03-01 21:33
Just an FYI I had a similar issue with the fill and stroke not being honored. By providing `fillType: 'literal'`, etc... the series then honored the colors I set. This isn't really explicit in the XYPlot / Series type documentation, although it is mentioned in the Scales and Data docs.

My .02 would be to make the color types (fill, stroke, opacity) default to literal instead of linear. Thoughts?

**Comment by WaldoJeffers** [comment] 2017-03-09 16:03
@akindr I couldn't agree more. If you specify `fill` and `stroke` attributes directly on your data items as [suggested in the docs](https://github.com/uber/react-vis/blob/master/docs/xy-plot.md#common-concepts), the colors will **not** be honored if you don't provide `fillType` and `strokeType` attributes set to `literal` on your `Series` component.

The Scales and Data docs do not help in this case. I don't know about the implications of your suggestion, but it seems to be right thing here. Whether or not this solution is adopted, users will always expect the rendered colors to match what they wrote in their code. 

Thanks for your help!

@mcnuttandrew I think this issue should be re-opened.
