### ISSUE TITLE
Line chart is out of the chart area

### ISSUE THREAD

**Issue by topvis** [uber/react-vis#543] opened 2017-08-11 21:18 UTC
I have an XYPlot with xDomain={[0, 5]}. The data and part of the code is here:
```
const data = [
  {x: 0, y: 1},
  {x: 1, y: 2},
  {x: 3, y: 9},
  {x: 6, y: 3},
]
<XYPlot height={300} width= {400} xDomain={[0, 5]} yDomain={[0, 10]}>
```
  
I want the line stops at x=5. Anything beyond 5 should be hidden. But as shown in the screenshot, the line sticks out a little beyond x=5. Any help would be appreciated.

![image](https://user-images.githubusercontent.com/5996531/29232185-4588978e-7eb8-11e7-9e97-46679623540c.png)

**Comment by mcnuttandrew** [comment] 2017-08-12 20:58
Hey @topvis,

This behavior is caused by having margins (in the case of your code snippet, the default ones)! To address simply drop in a [Border component](https://github.com/uber/react-vis/blob/master/docs/markdown/borders.md)!  Unfortunately, i think the borders accidentally got trimmed from the docs page, ill push up a fix.

**Comment by mcnuttandrew** [comment] 2017-08-12 21:07
Just updated the docs, http://uber.github.io/react-vis/#/documentation/api-reference/borders all should be in working order now. marking as resolved, feel free to re-open or continue discussion under the close as necessary

**Closed by mcnuttandrew** 2017-08-12 21:07 UTC

**Comment by topvis** [comment] 2017-08-13 05:08
@mcnuttandrew thanks for the solution. With Border component, I can its color to be the same as the background so the border can cover the small portion of the line that sticks out of the range. It works but does need some extra codes.

I wonder why not make it default that only the lines within the xDomain and yDomain are visible?

**Comment by mcnuttandrew** [comment] 2017-08-13 05:55
> I wonder why not make it default that only the lines within the xDomain and yDomain are visible?

The answer basically comes down to wanting to guarantee all rendered svg appears correctly. Eg, if a mark is right on the edge of the domain the whole circle should be visible (if it is within the bounds)

**Comment by topvis** [comment] 2017-08-14 02:53
@mcnuttandrew it makes sense for rendering things like Makers. But it doesn't look perfect if Line goes beyond the domain range. This is probably very subjective opinion.
